server:
  port: 5000
  health: http://localhost:5000/api/v2
  
telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: todo-backend
    brokers: localhost:9092
  consumer:
    groupId: todo-consumer
    allowAutoTopicCreation: true

database:
  mongo:
    uri: mongodb://root:root@localhost/note