server:
  port: 5000
  health: http://localhost:5000/todos

telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: todo-backend
    brokers:
      - port: 9092
        host: localhost
  consumer:
    groupId: todo-consumer
    allowAutoTopicCreation: true
